#general.import = [ "colors.toml" ]
[general]
import = [
    "~/.config/current/alacritty-theme.toml"
]

[env]
TERM = "alacritty"

[font]
normal = { family = "SF Mono", style = "Regular" }
bold = { family = "SF Mono", style = "Bold" }
italic = { family = "SF Mono", style = "Italic" }
size = 15

[window]
padding.x = 14
padding.y = 14
decorations = "None" 

[cursor]
style = "Beam"  
