#general.import = [ "colors.toml" ]
[general]
import = [
    "~/.config/current/alacritty-theme.toml"
]

[env]
TERM = "alacritty"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None" 
#opacity = 0.6

#[cursor]
#style = "Beam"
